#!/bin/sh

toplevel=`git rev-parse --show-toplevel`

reference_data=`tail -n +5 $toplevel/tests/N2/e_summary.reference \
                | egrep -v "[0-2][0-9]\:[0-5][0-9]\:[0-5][0-9]|time"`
                

ln -s $toplevel/src/mcci $toplevel/tests/N2/

nice $toplevel/tests/N2/mcci > $toplevel/tests/N2/out

new_data=`tail -n +5 $toplevel/tests/N2/e_summary \
          | egrep -v "[0-2][0-9]\:[0-5][0-9]\:[0-5][0-9]|time"`

if [ "$new_data" != "$reference_data" ]
then
    echo "Error: e_summary data do not match up with reference values"
    echo "In $toplevel/tests/N2"
    exit 1
else
    echo "Consistency test passed in tests/N2, cleaning up.."
    rm $toplevel/tests/N2/mcci
    rm $toplevel/tests/N2/weight
    rm $toplevel/tests/N2/civ_out
    rm $toplevel/tests/N2/cmin_dat
    rm $toplevel/tests/N2/convergence
    rm $toplevel/tests/N2/fracValue
    rm $toplevel/tests/N2/e_summary
    rm $toplevel/tests/N2/out
fi

